swiftmailer:
    default_mailer: dev
    mailers:
        dev:
            transport: smtp
            username:
            password:
            host: mail
            port: 1025
            encryption:
            auth_mode:
            sender_address:
            delivery_addresses: ['']
            disable_delivery: false
