networks:
  leantime:
    driver: bridge
    internal: false

services:
  mariadb:
    volumes:
      - .docker/dumps/uvdesk:/docker-entrypoint-initdb.d

  phpfpm:
    environment:
      # Cf. https://github.com/uvdesk/community-skeleton/blob/v1.1.3/.docker/config/php/php.ini
      - PHP_MEMORY_LIMIT=1024M

  leantime:
    image: leantime/leantime:latest
    networks:
      - frontend
      - leantime
    depends_on:
      - leantime-db
    ports:
      - '80'
    environment:
      - LEAN_DB_HOST=leantime-db
      - LEAN_DB_USER=db
      - LEAN_DB_PASSWORD=db
      - LEAN_DB_DATABASE=db
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_leantime.rule=Host(`leantime.${COMPOSE_DOMAIN}`)"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}_leantime.loadbalancer.server.port=80"
      # - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_leantime.middlewares=redirect-to-https"
      # - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  leantime-db:
    image: itkdev/mariadb:latest
    networks:
      - leantime
    ports:
      - '3306'
    volumes:
      - .docker/dumps/leantime:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
      - MYSQL_DATABASE=db
